(ns clojure-yahoo-finance.profiling
  (:use [clojure-yahoo-finance.core] :reload-all)
  (:use [clojure.contrib.profile]))

(def *sp500* 
     '(MMM AES AFL AKS T ABT ANF ADBE AMD AET A APD ARG AKAM AA AYE
 ATI AGN ALL ALTR MO AMZN AEE AEP AXP AIG AMT AMP ABC AMGN APH APC ADI
 AON APA AIV APOL AAPL AMAT ADM AIZ AN AZO ADSK ADP AVB AVY AVP BBT
 BJS BMC BHI BLL BAC BCR BAX BDX BBBY BMS BRK/B BBY BIG BIIB BDK HRB
 BA BXP BSX BMY BRCM BF/B CA CBG CBS CF CHRW CI CMS CNX CSX CVS COG
 CAM CPB COF CAH CFN CCL CAT CELG CNP CTL CEPH CHK CVX CME CB CINF
 CTAS CSCO C CTXS CLF CLX COH KO CCE CTSH CL CMCSA CMA CSC CPWR CAG
 COP ED STZ CEG GLW COST CVH CMI DTV DTE DHR DRI DVA DV DF DE DELL DNR
 XRAY DVN DO DFS DISCA D RRD DOV DOW DPS DD DUK DNB ETFC EMC EOG EQT
 EMN EK ETN ECL EIX EP ERTS EMR ETR EFX EQR EL EXC EXPE EXPD ESRX XOM
 FLIR FMC FTI FPL FDO FAST FDX FII FIS FITB FHN FSLR FE FISV FLS FLR F
 FRX FO BEN FCX FTR GME GCI GPS GD GE GIS GPC GNW GENZ GILD GS GR GT
 GOOG GWW HCP HAL HOG HAR HRS HIG HAS HCN HNZ HP HSY HES HPQ HD HON
 HRL DHI HSP HST HCBK HUM HBAN ITT ITW TEG INTC ICE IPG IBM IFF IGT IP
 INTU ISRG IVZ IRM JDSU JPM JBL JEC JNS JNJ JCI JNPR KLAC K KEY KMB
 KIM KG KSS KFT KR LLL LSI LH LM LEG LEN LUK LXK LIFE LLY LTD LNC LLTC
 LMT L LO LOW MTB WFR M MRO MAR MMC MI MAS MEE MA MAT MFE MKC MCD MHP
 MCK MJN MWV MHS MDT MRK MDP MET PCS MCHP MU MSFT MIL MOLX TAP MON MWW
 MCO MS MOT MUR MYL GAS NKE NRG NYX NBR NDAQ NOV NSM NTAP NYT NWL NEM
 NWSA NI NBL JWN NSC NU NTRS NOC NOVL NVLS NUE NVDA ORLY OXY ODP OMC
 ORCL OI PCAR PCG PNC PPG PPL PTV PLL PH PDCO PAYX BTU JCP PBCT POM
 PEP PKI PFE PM PNW PXD PBI PCL RL PX PCP PCLN PFG PG PGN PGR PLD PRU
 PEG PSA PHM QLGC QCOM PWR DGX STR Q RSH RRC RTN RHT RF RSG RAI RHI
 ROK COL ROP ROST RDC R SAI SCG SLM SWY CRM SNDK SLE SLB SCHW SNI SEE
 SHLD SRE SHW SIAL SPG SII SJM SNA SO LUV SWN SE S STJ SWK SPLS SBUX
 HOT STT SRCL SYK STI SUN SVU SYMC SYY TROW TE TJX TGT TLAB THC TDC
 TER TSO TXN TXT BK TMO TIF TWC TWX TIE TMK TSS TRV TSN USB UNP UPS X
 UTX UNH UNM URBN VFC VLO VAR VTR VRSN VZ VIA/B V VNO VMC WMT WAG DIS
 WPO WM WAT WPI WLP WFC WDC WU WY WHR WFMI WMB WIN WEC WYN WYNN XL XTO
 XEL XRX XLNX YHOO YUM ZMH ZION EBAY))

(defn download-sp500-one-day []
  (prof :downloading (blocking-query "2009-01-06" "2009-01-06" *sp500*)))


(defn download-aapl-one-month []
  (prof :downloading-aapl (blocking-query "2009-01-01" "2009-01-30" ["AAPL"])))

(defn download-aapl-one-year []
  (prof :downloading-aapl (blocking-query "2009-01-01" "2009-12-31" ["AAPL"])))



